ALTER TABLE holes ADD COLUMN IF NOT EXISTS tee2_club text DEFAULT '';
ALTER TABLE holes ADD COLUMN IF NOT EXISTS tee2_result text DEFAULT '';
ALTER TABLE holes ADD COLUMN IF NOT EXISTS tee2_penalty_type text DEFAULT '';
ALTER TABLE holes ADD COLUMN IF NOT EXISTS tee2_miss text DEFAULT '';
ALTER TABLE holes ADD COLUMN IF NOT EXISTS tee2_memo text DEFAULT '';
ALTER TABLE holes ADD COLUMN IF NOT EXISTS putt2_miss text DEFAULT '';
ALTER TABLE holes ADD COLUMN IF NOT EXISTS putt2_memo text DEFAULT '';
